// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sms-sender/ent/schema"
	"sms-sender/ent/sms"
	"sms-sender/ent/stoprequest"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	smsFields := schema.Sms{}.Fields()
	_ = smsFields
	// smsDescSentAt is the schema descriptor for sentAt field.
	smsDescSentAt := smsFields[3].Descriptor()
	// sms.DefaultSentAt holds the default value on creation for the sentAt field.
	sms.DefaultSentAt = smsDescSentAt.Default.(time.Time)
	stoprequestFields := schema.StopRequest{}.Fields()
	_ = stoprequestFields
	// stoprequestDescStopDate is the schema descriptor for stop_date field.
	stoprequestDescStopDate := stoprequestFields[1].Descriptor()
	// stoprequest.DefaultStopDate holds the default value on creation for the stop_date field.
	stoprequest.DefaultStopDate = stoprequestDescStopDate.Default.(time.Time)
}
