// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sms-sender/ent/stoprequest"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StopRequestCreate is the builder for creating a StopRequest entity.
type StopRequestCreate struct {
	config
	mutation *StopRequestMutation
	hooks    []Hook
}

// SetRecipient sets the "recipient" field.
func (src *StopRequestCreate) SetRecipient(s string) *StopRequestCreate {
	src.mutation.SetRecipient(s)
	return src
}

// SetStopDate sets the "stop_date" field.
func (src *StopRequestCreate) SetStopDate(t time.Time) *StopRequestCreate {
	src.mutation.SetStopDate(t)
	return src
}

// SetNillableStopDate sets the "stop_date" field if the given value is not nil.
func (src *StopRequestCreate) SetNillableStopDate(t *time.Time) *StopRequestCreate {
	if t != nil {
		src.SetStopDate(*t)
	}
	return src
}

// Mutation returns the StopRequestMutation object of the builder.
func (src *StopRequestCreate) Mutation() *StopRequestMutation {
	return src.mutation
}

// Save creates the StopRequest in the database.
func (src *StopRequestCreate) Save(ctx context.Context) (*StopRequest, error) {
	src.defaults()
	return withHooks(ctx, src.sqlSave, src.mutation, src.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (src *StopRequestCreate) SaveX(ctx context.Context) *StopRequest {
	v, err := src.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (src *StopRequestCreate) Exec(ctx context.Context) error {
	_, err := src.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (src *StopRequestCreate) ExecX(ctx context.Context) {
	if err := src.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (src *StopRequestCreate) defaults() {
	if _, ok := src.mutation.StopDate(); !ok {
		v := stoprequest.DefaultStopDate
		src.mutation.SetStopDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (src *StopRequestCreate) check() error {
	if _, ok := src.mutation.Recipient(); !ok {
		return &ValidationError{Name: "recipient", err: errors.New(`ent: missing required field "StopRequest.recipient"`)}
	}
	if _, ok := src.mutation.StopDate(); !ok {
		return &ValidationError{Name: "stop_date", err: errors.New(`ent: missing required field "StopRequest.stop_date"`)}
	}
	return nil
}

func (src *StopRequestCreate) sqlSave(ctx context.Context) (*StopRequest, error) {
	if err := src.check(); err != nil {
		return nil, err
	}
	_node, _spec := src.createSpec()
	if err := sqlgraph.CreateNode(ctx, src.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	src.mutation.id = &_node.ID
	src.mutation.done = true
	return _node, nil
}

func (src *StopRequestCreate) createSpec() (*StopRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &StopRequest{config: src.config}
		_spec = sqlgraph.NewCreateSpec(stoprequest.Table, sqlgraph.NewFieldSpec(stoprequest.FieldID, field.TypeInt))
	)
	if value, ok := src.mutation.Recipient(); ok {
		_spec.SetField(stoprequest.FieldRecipient, field.TypeString, value)
		_node.Recipient = value
	}
	if value, ok := src.mutation.StopDate(); ok {
		_spec.SetField(stoprequest.FieldStopDate, field.TypeTime, value)
		_node.StopDate = value
	}
	return _node, _spec
}

// StopRequestCreateBulk is the builder for creating many StopRequest entities in bulk.
type StopRequestCreateBulk struct {
	config
	builders []*StopRequestCreate
}

// Save creates the StopRequest entities in the database.
func (srcb *StopRequestCreateBulk) Save(ctx context.Context) ([]*StopRequest, error) {
	specs := make([]*sqlgraph.CreateSpec, len(srcb.builders))
	nodes := make([]*StopRequest, len(srcb.builders))
	mutators := make([]Mutator, len(srcb.builders))
	for i := range srcb.builders {
		func(i int, root context.Context) {
			builder := srcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StopRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, srcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, srcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, srcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (srcb *StopRequestCreateBulk) SaveX(ctx context.Context) []*StopRequest {
	v, err := srcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (srcb *StopRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := srcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (srcb *StopRequestCreateBulk) ExecX(ctx context.Context) {
	if err := srcb.Exec(ctx); err != nil {
		panic(err)
	}
}
