// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sms-sender/ent/predicate"
	"sms-sender/ent/stoprequest"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StopRequestDelete is the builder for deleting a StopRequest entity.
type StopRequestDelete struct {
	config
	hooks    []Hook
	mutation *StopRequestMutation
}

// Where appends a list predicates to the StopRequestDelete builder.
func (srd *StopRequestDelete) Where(ps ...predicate.StopRequest) *StopRequestDelete {
	srd.mutation.Where(ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *StopRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, srd.sqlExec, srd.mutation, srd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *StopRequestDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *StopRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(stoprequest.Table, sqlgraph.NewFieldSpec(stoprequest.FieldID, field.TypeInt))
	if ps := srd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	srd.mutation.done = true
	return affected, err
}

// StopRequestDeleteOne is the builder for deleting a single StopRequest entity.
type StopRequestDeleteOne struct {
	srd *StopRequestDelete
}

// Where appends a list predicates to the StopRequestDelete builder.
func (srdo *StopRequestDeleteOne) Where(ps ...predicate.StopRequest) *StopRequestDeleteOne {
	srdo.srd.mutation.Where(ps...)
	return srdo
}

// Exec executes the deletion query.
func (srdo *StopRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{stoprequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *StopRequestDeleteOne) ExecX(ctx context.Context) {
	if err := srdo.Exec(ctx); err != nil {
		panic(err)
	}
}
