// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Sms is the predicate function for sms builders.
type Sms func(*sql.Selector)

// StopRequest is the predicate function for stoprequest builders.
type StopRequest func(*sql.Selector)
